#!/bin/bash

GREEN='\033[0;32m'
YELLOW='\033[1;33m'

RESET='\033[0m'

# Get the current directory
current_dir=$(pwd)

# Set default port to 8000 if no argument provided
port=${1:-8000}

output=$(tunip)
echo -e "Tunip:${GREEN} $output ${RESET}"


# Run python3 -m http.server with the current directory as document root and specified/defaulted port
python3 -m http.server "$port" -d "$current_dir"
